import React from 'react'
import ReactDOM from 'react-dom/client'
import { BrowserRouter } from 'react-router-dom'
import { Amplify } from 'aws-amplify'
import App from './App.jsx'
import './index.css'
import '@aws-amplify/ui-react/styles.css'

// Configure Amplify with outputs from backend deployment
// This file is auto-generated by Amplify during backend deployment
async function configureAmplify() {
  try {
    const outputs = await import('../amplify_outputs.json')
    Amplify.configure(outputs.default)
  } catch (e) {
    console.warn('Amplify outputs not found. Backend may not be deployed yet.')
  }
}

configureAmplify().then(() => {
  ReactDOM.createRoot(document.getElementById('root')).render(
    <React.StrictMode>
      <BrowserRouter>
        <App />
      </BrowserRouter>
    </React.StrictMode>,
  )
})
